packages:
  - "frontend/app/*"
  - "frontend/kapis"
  - "frontend/packages/*"
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  '@tarojs/binding': true
  '@tarojs/cli': true
  core-js: true
  core-js-pure: true
  esbuild: true
  msgpackr-extract: true
  sharp: true
